apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-store-reader
  namespace: platform-secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eso-store-reader
  namespace: platform-secrets
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eso-store-reader
  namespace: platform-secrets
subjects:
- kind: ServiceAccount
  name: eso-store-reader
  namespace: platform-secrets
roleRef:
  kind: Role
  name: eso-store-reader
  apiGroup: rbac.authorization.k8s.io
