apiVersion: policies.kyverno.io/v1
kind: ValidatingPolicy
metadata:
  name: check-labels
spec:
  validationActions:
    - Deny
  matchConstraints:
    resourceRules:
      - apiGroups: ["apps"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["deployments"]
  validations:
    - message: "required deployment labels are missing: app, environment, owner"
      expression: >-
        has(object.metadata.labels) &&
        'app' in object.metadata.labels &&
        'environment' in object.metadata.labels &&
        'owner' in object.metadata.labels

    - message: "required pod labels are missing: app, environment, owner"
      expression: >-
        has(object.spec.template.metadata.labels) &&
        'app' in object.spec.template.metadata.labels &&
        'environment' in object.spec.template.metadata.labels  &&
        'owner' in object.spec.template.metadata.labels
