apiVersion: policies.kyverno.io/v1
kind: ValidatingPolicy
metadata:
  name: validate-probes
  annotations:
    policies.kyverno.io/title: Validate Probes
    argocd.argoproj.io/sync-wave: 0 
spec:
  validationActions:
    - Deny
  autogen:
    podControllers:
      controllers:
        - deployments
        - daemonsets
        - statefulsets
        - jobs
        - cronjobs
  evaluation:
    background:
      enabled: false
  matchConstraints:
    resourceRules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        resources:
          - pods
        operations:
          - CREATE
          - UPDATE
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kyverno
            - kube-system
  validations:
    - message: "Liveness and readiness probes cannot be the same."
      expression: >-
        !object.spec.containers.exists(container,
          has(container.readinessProbe) &&
          has(container.livenessProbe) &&
          container.readinessProbe == container.livenessProbe
        )
