apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/devshinthant/internal-developer-platform.git
    targetRevision: main
    path: platform/policies
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

