apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo-2
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/devshinthant/internal-developer-platform.git
    targetRevision: main
    path: charts/pod-info-2
  destination:
    server: https://kubernetes.default.svc
    namespace: applications
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
