apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api
  labels:
    app: node-api
    environment: dev
    owner: dev-team
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
        environment: dev
        owner: dev-team
    spec:
      containers:
        - name: node-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: PORT
              value: "{{ .Values.service.targetPort }}"
            - name: DEMO_SECRET
              valueFrom:
                secretKeyRef:
                  name: node-api-secret
                  key:  DEMO_SECRET
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
